# Generated by Django 4.2.7 on 2023-11-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('category', models.IntegerField(choices=[(1, 'Foundation'), (2, 'Concealer'), (3, 'Compact'), (4, 'Eye Shadow'), (5, 'Lipstick'), (6, 'Highlighter'), (7, 'Eye Kajal'), (8, 'Eyeliner')])),
                ('is_active', models.BooleanField(default=True, verbose_name='available')),
                ('pimage', models.ImageField(upload_to='image')),
            ],
        ),
    ]
